### ISSUE TITLE
Stop polly on test_skip events

### ISSUE THREAD

**Issue by stephenh** [gribnoysup/setup-polly-jest#24]
On jest-circus, it looks like `test_start` is fired even if a test is going to be skipped, and then `test_skipped` is fired right after it.

We were getting "overlapping polly instance" errors until locally patching `jest-enviornment-polly` to also tear down when `test_skipped` goes by:

```
      if ((event.name === "test_done" || event.name === "test_skip") && this.pollyGlobals.pollyContext.polly) {
        await this.pollyGlobals.pollyContext.polly.stop();
        this.pollyGlobals.pollyContext.polly = null;
      }
```

Fwiw I'm surprised that `test_start` is fired for skipped tests, but :shrug: , I assume it's a jest-circus change, given we didn't have this issue on jest 26.

**Comment by gribnoysup** [comment]
Hmmm, yeah, can confirm, thanks for reporing the issue! This sounds like a possible unintentional breaking change in jest, I'll try to create a small repro, find when it started and open an issue on their side. Even if it was intentional, I'd want to hear from them why the change was made to better understand how to handle it, I'd prefer this library not to start and then teardown polly if the suite is skipped if possible to avoid that

**Comment by stephenh** [comment]
Ah yeah, good idea to follow up with Jest!

**Comment by gribnoysup** [comment]
Okay, so seems like this was happening all the way back even with jest-circus@25 so I'll add a fix for now that starts polly in all cases and stops it if the test was skipped. It's a bit unfortunate though that this needs to happen, so I'll think about how this can be handled better in the future when I have a bit more time to focus on this stuff

**Comment by stephenh** [comment]
Great, thanks!
