### ISSUE TITLE
Can I use this to run jasmine tests run against a browser?

### ISSUE THREAD

**Issue by filipeamoreira** [gribnoysup/setup-polly-jest#4]
I'm trying to use Polly.JS with Jasmine and Karma. So my jasmine tests run against a real instance of Chrome using Karma. However, I cannot make it work. If I run jasmine outside of the browser, only via node, it works. 

So I'm wondering if I'm missing some additional configuration or even if I'm using this adapter in a way it was not intended.

Thank you

**Comment by gribnoysup** [comment]
Hi @filipeamoreira! Tbh I'm not the biggest jasmine/karma user so it's hard for me to give you an answer right away 😅 

It would be nice if you could create a small reproduction so I could check it out in more detail. If you can't, that's okay, I'll try to jump on this as soon as I have some free time 👌

**Comment by filipeamoreira** [comment]
Thank you for the reply @gribnoysup. I have a reproduction repo here: https://github.com/filipeamoreira/karma-nock/tree/pollyjs-integration.

Using the `fetch` adapter coupled with the `fs` persister worked fine. However, I could not make it work with Karma and the `rest` persister. I have the node cli tool running, but requests never hit the server. I event tried hard coding the `Polly.register(RESTPersister);` inside the `createTestFnProxy`  on line 100. But had no luck. 

Thank you so much for taking the time to check this.

**Comment by gribnoysup** [comment]
Hey @filipeamoreira, I submitted a PR (https://github.com/filipeamoreira/karma-nock/pull/1) against your Polly branch that should clarify you how to setup REST persister with Polly. There were a couple of things that I changed to make it work:

When using REST persister, you need Polly server running in parallel with your tests, otherwise, there is nothing that can save and replay tests when Polly client checks for snapshots. To make it work I used `start-server-and-test` library, it's a neat tool that starts Polly server first and then proceeds with running tests when Polly server is ready.

There were a bunch of small issues also: fetch adapter wasn't registered and there was a typo in logging option name, so it was a little bit hard to debug at first 😅 

I also changed `recordIfMissing` option and changed the mode to replay. I did this purely for testing purposes, as it was easier that way to check if everything is working correctly and the snapshots are recorded and replayed. You can freely change those options as they don't affect the main setup

**Comment by filipeamoreira** [comment]
Thank you very much @gribnoysup. I've merged your PR and it works as expected. Thank you for the pointers in regards to the `start-server-and-test` package.

I was not aware that while in `record` mode it would not `replay` the recordings. They do make sense to me now. 

Thanks
